Enable all warnings and convert them to errors
Add `-Wall -Werror` to the C flags in order to enable all warnings and
convert them to errors. All except for annoying
`declaration-after-statement` warnings, which we continue to suppress
altogether.

Unfortunately, this causes errors from `clang-tidy` on Linux, generating
errors like:

```
error: unknown warning option '-Wimplicit-fallthrough=3'; did you mean '-Wimplicit-fallthrough'?
error: unknown warning option '-Wno-stringop-truncation'; did you mean '-Wno-format-truncation'?
error: unknown warning option '-Wshadow=compatible-local'; did you mean '-Wshadow-uncaptured-local'?
```

So add `bear` configuration files to remove `-Werror` when using gcc.
Update the `compile_commands.json` target to detect Bear 3 (as currently
on the CI instances) and use the JSON config file and otherwise use the
YAML config file supported by Bear 4.

While at it, use `run-clang-tidy` to run the checks across file in
parallel, greatly reducing execution time.